### ISSUE TITLE
Dependency on leveldb?

### ISSUE THREAD

**Issue by saikyun** [pepe/chidi#7]
This is what I currently get when trying to install chidi.
```
sudo jpm install chidi
...
linking build/tahani.so...
/usr/bin/ld: cannot find -lleveldb
collect2: error: ld returned 1 exit status
```

**Comment by pepe** [comment]
Oh, now I understand. I need to deprecate this repository; thank you for the head-up. The canonical version is on sourcehut https://git.sr.ht/~pepe/chidi, as I am moving away from the GH.

**Comment by pepe** [comment]
And I would like to apologize.
